version: "2.3"

networks:
  default:
    external:
      name: ros-network
                
volumes:
  workspace:

services:

  deepstack:
    image: deepquestai/deepstack${TAG}
    container_name: deepstack
    init: true
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/datastore"
    environment:
      - "VISION-SCENE=True"
      - "VISION-DETECTION=True"
      - "VISION-FACE=True"
    ports:
      - "5000:5000"
    runtime: "nvidia"

  deepstack_ui:
    image: robmarkcole/deepstack-ui
    container_name: deepstack_ui
    restart: unless-stopped
    environment: 
      - DEEPSTACK_IP=deepstack
      - DEEPSTACK_PORT=5000
      - DEEPSTACK_API_KEY=""
      - DEEPSTACK_TIMEOUT=20
      #- DEEPSTACK_CUSTOM_MODEL=fire
      - DEEPSTACK_UI_DEBUG_MODE=True
    ports:
      - '8501:8501'